steps:
  - id: build-image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - asia-southeast1-docker.pkg.dev/$PROJECT_ID/roadwatch/roadwatch-web:$BUILD_ID
      - .
  - id: push-image
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia-southeast1-docker.pkg.dev/$PROJECT_ID/roadwatch/roadwatch-web:$BUILD_ID
  - id: deploy-cloud-run
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - roadwatch-web
      - --project=$PROJECT_ID
      - --region=asia-southeast1
      - --platform=managed
      - --image=asia-southeast1-docker.pkg.dev/$PROJECT_ID/roadwatch/roadwatch-web:$BUILD_ID
      - --allow-unauthenticated
      - --port=8000
      - --cpu=2
      - --memory=4Gi
      - --timeout=3600
      - --concurrency=1
      - --min=0
      - --max=2
      - --set-env-vars=ROADWATCH_CLOUD_MODE=web_demo,ROADWATCH_DISABLE_AUDIO=1,ROADWATCH_MAX_UPLOAD_MB=25,ROADWATCH_GCS_ASSET_BUCKET=c3-roadwatch-162-roadwatch-assets
images:
  - asia-southeast1-docker.pkg.dev/$PROJECT_ID/roadwatch/roadwatch-web:$BUILD_ID
options:
  logging: CLOUD_LOGGING_ONLY
