from __future__ import annotations

import json
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EVALUATION = ROOT / "evaluation"
OUTPUT = ROOT / "docs" / "rw05_rw10_annotation_report.md"
RW05_QUEUES = (
    "rw05_night_annotation_queue.json",
    "rw05_rain_night_annotation_queue.json",
    "rw05_traffic_multi_annotation_queue.json",
)


def load(name: str) -> dict:
    return json.loads((EVALUATION / name).read_text(encoding="utf-8"))


def rw05_rows() -> tuple[list[str], int, float, float]:
    rows: list[str] = []
    total_windows = 0
    total_planned = 0.0
    total_verified = 0.0
    for name in RW05_QUEUES:
        payload = load(name)
        windows = payload.get("windows", [])
        counts = Counter(
            str(window.get("primary_review", {}).get("status", "missing"))
            for window in windows
        )
        planned = sum(float(window.get("coverage_seconds", 0)) for window in windows)
        verified = sum(
            float(window.get("coverage_seconds", 0))
            for window in windows
            if window.get("primary_review", {}).get("status") == "verified"
        )
        rows.append(
            f"| `{name}` | {len(windows)} | {counts['pending']} | "
            f"{counts['verified']} | {counts['rejected']} | {planned:.1f} | {verified:.1f} |"
        )
        total_windows += len(windows)
        total_planned += planned
        total_verified += verified
    return rows, total_windows, total_planned, total_verified


def quality_gate_rows() -> list[str]:
    names = sorted(path.name for path in EVALUATION.glob("rw05_quality_gate*.json"))
    names.append("rw10_quality_gate.json")
    rows = []
    for name in names:
        payload = load(name)
        rows.append(f"| `{name}` | `{payload.get('status', 'missing')}` |")
    return rows


def main() -> int:
    rw05, windows, planned, verified = rw05_rows()
    rw10 = load("rw10_lane_annotation_queue.json")
    records = rw10.get("records", [])
    statuses = Counter(str(record.get("review_status", "missing")) for record in records)
    gate_rows = quality_gate_rows()
    generated = datetime.now(timezone.utc).isoformat()
    status = "PASS" if verified == planned and statuses["verified"] == len(records) else "NOT PASS"
    report = f"""# RW-05 and RW-10 Annotation Validation Report

Generated by `scripts/generate_annotation_report.py` at `{generated}`. This report counts
annotation workflow states, not JSON fields.

## RW-05 Event Windows

| Queue | Windows | Pending | Verified | Rejected | Planned seconds | Verified seconds |
|---|---:|---:|---:|---:|---:|---:|
{chr(10).join(rw05)}
| **Total** | **{windows}** |  |  |  | **{planned:.1f}** | **{verified:.1f}** |

## RW-10 Lane Frames

| Total | Pending | Verified | Rejected | Missing status |
|---:|---:|---:|---:|---:|
| {len(records)} | {statuses['pending']} | {statuses['verified']} | {statuses['rejected']} | {statuses['missing']} |

## Current Quality Gates

| Artifact | Status |
|---|---|
{chr(10).join(gate_rows)}

## Decision

**{status}.** RW-05 requires verified event windows and RW-10 requires reviewed lane count,
ego boundaries and uncertainty labels. A document-level owner statement does not replace
the per-window/per-frame review state stored in the evaluation queues.
"""
    OUTPUT.write_text(report, encoding="utf-8")
    print(json.dumps({
        "output": str(OUTPUT), "rw05_windows": windows,
        "rw05_verified_seconds": verified, "rw10_records": len(records),
        "rw10_verified": statuses["verified"], "status": status,
    }, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
